import Redis from "ioredis";

const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";
const NOTIFICATION_CHANNEL = "user:notifications";

async function sendMockNotification(userId: string) {
  const redis = new Redis(REDIS_URL);

  const mockNotification = {
    id: `mock-notification-${Date.now()}`,
    title: "New Message from Admin",
    message: "This is a mock notification generated by a script!",
    read: false,
    type: "INFO",
    link: "/dashboard/notifications",
    createdAt: new Date().toISOString(),
  };

  const messagePayload = {
    userId: userId,
    notification: mockNotification,
  };

  try {
    const message = JSON.stringify(messagePayload);
    await redis.publish(NOTIFICATION_CHANNEL, message);
    console.log(`Successfully published mock notification for user: ${userId}`);
    console.log("Notification payload:", messagePayload);
  } catch (error) {
    console.error("Failed to publish mock notification:", error);
    process.exit(1);
  } finally {
    await redis.quit();
  }
}

// --- Usage ---
const targetUserId = process.argv[2]; // Get userId from command-line argument

if (!targetUserId) {
  console.error("Usage: ts-node scripts/send-mock-notification.ts <userId>");
  process.exit(1);
}

sendMockNotification(targetUserId).catch((err) => {
  console.error("Script execution failed:", err);
  process.exit(1);
});
